# Generated by Django 3.0.3 on 2020-04-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_userpics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpics',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
